api {
  baseUrl = "https://jsonplaceholder.typicode.com"
  timeout = 30000

  # SSL настройки (опционально)
  keystore = ""
  truststore = ""
  keystorePassword = ""
  truststorePassword = ""
}

pekko {
  loglevel = "INFO"
  actor {
    provider = "local"
  }
}